language: node_js
branches:
  only:
    - master
  except:
    - '*'
install:
  - npm install -g firebase-tools
script:
  - npm ci
  - (cd client && npm run build)
  - firebase use
  - firebase deploy --token $FIREBASE_TOKEN