language: node_js
branches:
  only:
    - master
  except:
    - '*'
install:
  - npm install -g firebase-tools
script:
  - npm ci
  - (cd client && npm run build)
after_success:
  - firebase use claybensonme
  - firebase deploy --token $FIREBASE_TOKEN