language: node_js
node_js:
  - "12.16.1"
branches:
  only:
    - master
script:
  - npm ci
install:
  - npm install -g firebase-tools
after_success:
  - firebase use default
  - firebase deploy --token $FIREBASE_TOKEN