language: node_js
node_js:
  - "12.16.1"
branches:
  only:
    - master
install:
  - npm install -g firebase-tools
script:
  - npm ci
  - (cd client && npm run build)
after_success:
  - firebase use default
  - firebase deploy --token $FIREBASE_TOKEN